version: '3'

networks:
  proxynet:
    driver: bridge

services:
  chrome-haproxy:
    build:
      context: haproxy
    networks:
      - proxynet
    ports:
      - "${CHROME_RDP_PORT:-3000}:3000"
    restart: unless-stopped
    depends_on:
      - chrome-vpn1
      - chrome-vpn2
      - chrome-vpn3
      - chrome-vpn4
    environment:
      FRONTEND_PORT: 3000
      BACKENDS_PORT: 3000
      BACKENDS: "chrome-vpn1 chrome-vpn2 chrome-vpn3 chrome-vpn4"
      HTTPCHK: "HEAD /health"
      HTTPCHKPORT: 8080

  proxy-haproxy:
    build:
      context: haproxy
    networks:
      - proxynet
    ports:
      - "${PROXY_PORT:-3001}:3001"
    restart: unless-stopped
    depends_on:
      - chrome-vpn1
      - chrome-vpn2
      - chrome-vpn3
      - chrome-vpn4
    environment:
      FRONTEND_PORT: 3001
      BACKENDS_PORT: 3001
      BACKENDS: "chrome-vpn1 chrome-vpn2 chrome-vpn3 chrome-vpn4"
      HTTPCHK: "HEAD /health"
      HTTPCHKPORT: 8080

  chrome-vpn1: &chrome-vpn
    image: ericdraken/chrome-vpn:armv7
    restart: unless-stopped
    cap_add:
      - NET_ADMIN # Needed for VPN tunnel adapter
    networks:
      - proxynet
    expose:
      - 3000 # Chrome Debug Protocol port
      - 3001 # Chrome bypass port
      - 8080 # Actuator port
    dns:
      - "${DNS_SERVER_1:-9.9.9.9}"
      - "${DNS_SERVER_2:-1.1.1.1}"
    environment:
      VPN_USER: "$VPN_USER"
      VPN_PASS: "$VPN_PASS"
        # curl -s https://api.nordvpn.com/server | jq -c '.[] | .country' | jq -s -a -c 'unique | .[]'
      COUNTRY: "${COUNTRY:-United States}"
        # curl -s https://api.nordvpn.com/server | jq -c '.[] | .categories[].name' | jq -s -a -c 'unique | .[]'
      OPENVPN_OPTS: "${OPENVPN_OPTS:---pull-filter ignore \"ping-restart\" --ping-exit 180}"
      CATEGORY: "${CATEGORY:-Standard VPN servers}"
      RANDOM_TOP: "${RANDOM_TOP:-10}"
      RECREATE_VPN_CRON: "${RECREATE_VPN_CRON:-''}"
        # ip route | awk '!/ (docker0|br-)/ && /src/ {print $1}'
      NETWORK: "${NETWORK:-192.168.0.0/24}"
      TZ: "${TZ:-America/Vancouver}"
      TEST_URL: "${TEST_URL:-https://1.1.1.1/}"
      MAX_CPU_PERCENT: 24
      MAX_MEMORY_PERCENT: 24
      MAX_CONCURRENT_SESSIONS: 3

  chrome-vpn2:
    <<: *chrome-vpn

  chrome-vpn3:
    <<: *chrome-vpn

  chrome-vpn4:
    <<: *chrome-vpn

  echo:
    build:
      context: echo
    restart: unless-stopped
    networks:
      - proxynet
    expose:
      - 8080